name: Release

on:
  push:
    branches:
      - '**'

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Latest Release Version
      id: get-latest-release
      uses: fangqiuming/latest-release-version@v1.1.1
    - run: echo ${{ steps.get-latest-release.outputs.version }}
    - name: Check shell and Windows version
      run: |
        (Get-Content -Path "src/__init__.py" -Raw) -match 'def version\(self\) -> mobase\.VersionInfo:\s*return mobase\.VersionInfo\((\d+),\s*(\d+),\s*(\d+)\)' | Out-Null; "$($Matches[1]).$($Matches[2]).$($Matches[3])"
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.0.0
    - name: Set up Python ${{ matrix.config.py }}
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy mobase-stubs PyQt6
    - name: Typecheck
      run: |
        mypy $(git ls-files '*.py')
