name: Typecheck

on: [push, workflow_dispatch]

jobs:
  typecheck:
    name: MO ${{ matrix.config.mo }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { py: '3.8.7',  qt: '5', qtm: '15.2', mo: '2.4.0', md: '' }
          - { py: '3.11.5', qt: '6', qtm: '5.3',  mo: '2.5.0', md: '.dev16' }
          - { py: '3.12.3', qt: '6', qtm: '7.1',  mo: '2.5.2', md: '' }
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: ${{ matrix.config.qt }}.${{ matrix.config.qtm }}
    - name: Set up Python ${{ matrix.config.py }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.config.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --force-reinstall pip
        pip install mypy mobase-stubs==${{ matrix.config.mo }}${{ matrix.config.md }} PyQt${{ matrix.config.qt }}==${{ matrix.config.qt }}.${{ matrix.config.qtm }}
    - name: Typecheck
      run: |
        mypy $(git ls-files '*.py')
